### PR TITLE
Add support for sharding

### PR DESCRIPTION
**Pull request by Headline**
As this bot continues to grow, it will eventually need to be sharded (of course!).

This is a swing at a primitive implementation of this and it is currently running on the live bot. I've tested bot functionality to a basic level, but ultimately time will tell whether or not any issues arise.

The most significant changes involve all of our statistics tracking, as `client.guilds.cache.size` will no longer fetch the total guild count. All instances of this should be covered in the patch.

This also includes a change to the client/guild blacklisting feature. Historically we've always written to the json file every time it was modified, but now only the shard that receives the command is allowed to modify the file, all of the other shards receive a notice through `GuildBlacklist#addToCache`. In theory, our blacklists should all remain up-to-date across all shards.

### CODE REVIEW

**Comment by Headline** [comment]
@rumblefrog can I get a brief once-over from you regarding this pr?

**Comment by rumblefrog** [comment]
Aside from the unusual obsessive async use, this looks like 🚢

**Comment by Headline** [comment]
This patch is big, because of it we've now reached version `2.1.0`

Behavior should not have changed in a breaking way. If you're upgrading to this patch go ahead and run npm install to update dependencies and you should be set.

**Comment by Headline** [comment]
This patch is big, because of it we've now reached version `2.1.0`

**Pull request merged**
