### PR TITLE
Add an online file input code option to compile

### PR DESCRIPTION
**Pull request by Sighery**
This feature allows pulling code to execute from some online paste tool such as Hastebin, or Pastebin.

The way I've implemented this is by adding another special character, in this case, to keep it somewhat in the spirit of Bash (as with the pipe character already used to pass input `|`), I've used `<`, the redirection input character to pass in the URL. An example would be:

```
;compile javascript < https://hastebin.com/raw/kixigahite
```

I've implemented this because a few days ago I wanted to show some Linked List implementation I wrote in JavaScript, and I couldn't because the code ended up being longer than 2000 characters, the limit for Discord's messages. This allows just having the bot pull the code from some online paste tool and run it, no matter if it goes over 2000 characters, which it might if your code depends on a bunch of classes and functions.

---

Now, some implementation details that should be noted:

If a URL is passed, it will try to pull the code from there. If successful, it will ignore any given code block in the message. I guess another option would be to merge both if they are in the message, that way you could pull, say, the jQuery code, and then have your code block that runs after it, and as such this would work kind of like importing dependencies. I have not implemented that, however. With this code it will simply ignore any code block. If the "import" kinda thing sounds good maybe it would be a good idea to be able to chain URLs to pull from.

If the URL is invalid, or the request failed for some reason, it will just skip and go over to the previous code of trying to find a code block and using that (or displaying an error if also unavailable).

And last, this redirection input feature **will only** work if it's passed before the pipe. You can still use pipe, and chain both things such as:

```
;compile javascript < https://hastebin.com/raw/kixigahite | Some input data here, yay!
```

But in the spirit of keeping with Bash logic, if you pass in the redirection output _after_ the pipe, it will just assume it's all normal characters and data and interpret it as part of the pipe input data.

### CODE REVIEW

**Comment by Sighery** [comment]
Not quite a fan of static analysis, but then again I haven't used those kind of tools much and the times I did they'd usually report silly stuff, so I _might_ be biased. As for the current ones being [reported by the tool here](https://app.codacy.com/app/michaelwflaherty/discord-compiler-bot/pullRequest?prid=3574230), not much I can do about them.

There were already a few hits in that loop before, I simply added a few more lines there that make use of `args` and the index being looped, so it pops out as new errors, when really it's the same error that already existed but used a few more times.

One possible way to solve it, since the tool doesn't seem to like square bracket notation, would be to use a `for of` loop so you get the items directly, instead of having to access the array with the index. But then you lose the ability to skip the first two items, as the code does. An option would be to just take a slice of the array while passing it to the loop, so it doesn't include the first two results, such as: `for (item of args.slice(2))`.

I don't particularly like looping with indexes, but in this one case I think the other options would be less readable, even though they'd probably remove these static analysis errors.

**Comment by Headline** [comment]
Feel free to ignore that check; It was experimental

**Comment by Sighery** [comment]
Yep. I would have written unit tests on it to prove it, but not sure how experienced you are with unit tests, or if you even want them, since you currently have none.

**Comment by Headline** [comment]
We currently do not have any unit testing, but it is planned for the future. Thank you!

**Pull request merged**
